[metadata]
name = toonio
version = 0.1.0
author = Mohit Prajapat
description = 
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/mohitprajapat2001/toonio
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
include_package_data = true
python_requires = >=3.10

[options.packages.find]
exclude =
    demo
    tests

[tool:pytest]
testpaths =
    tests
python_files =
    test_*.py
python_classes =
    Test*
python_functions =
    test_*
addopts =
    -v
    --tb=short
    --strict-markers
log_cli = true
log_cli_level = INFO